### PR TITLE
Change debug print to hex

### PR DESCRIPTION
**Pull request by AndreasBomholtz**
I change the debug print to show te hex bytes instead of the string.

### CODE REVIEW

**Comment by rcloran** [comment]
It would be preferable to open a separate PR for the extra comments.

**Comment by rcloran** [comment]
I'm curious why you changed from .hex() to binascii.hexlify().

**Comment by rcloran** [comment]
Apparently by resolving conflicts here on the PR, I've updated your branch, which was surprising to me.

**Comment by AndreasBomholtz** [comment]
It was because the tests failed for the old python version. So I changed it
to something that worked for all three versions.

Den 3. maj 2017 17.25 skrev "Russell Cloran" <notifications@github.com>:

**Comment by rcloran** [comment]
Ah, OK, that makes sense. I didn't check the previous travis results.

Thanks!

**Pull request merged**
