### PR TITLE
Add error reporting when database isn't provided when needed

### PR DESCRIPTION
**Pull request by halkeye**
New output:
```
Usage: bellows devices [OPTIONS]

Error: Invalid value for "-D" / "--database": Path "/home/halkeye/.config/bellows/app.db" does not exist.
```

### CODE REVIEW

**Comment by halkeye** [comment]
Looks like the CI broke on installing six for linting

I just tried it locally (`tox -e lint`) and it had no issues.

**Comment by rcloran** [comment]
Without this commit, the database is automatically initialized when it doesn't exist -- for example, when setting up a new network/adding the first node to a new network. That makes it easier to get going... but, I've received enough "bugs" related to this that maybe checking its existence is the right way to go. Let's try it.

**Comment by halkeye** [comment]
If the directory doesn't exist it spits out a large stack trace with no indication on what the path should be.

**Comment by rcloran** [comment]
Thanks!

**Pull request merged**
